n = input('Digite algo: ')
print('O caractere digitado é numerico ', n.isnumeric())
print('O caractere digitado é apenas letra ', n.isalpha())
print('O carctere digitado possui letra ou numero ', n.isalnum())
print('O caractere digitado esta em letras maiusculas ', n.isupper())
print('O caractere digitado esta em letras minusculas ', n.islower())
print('O caractere digitado é um espaço ', n.isspace())
print('O caractere digitado é um digito ', n.isdigit())
print('O caractere digitado é um titulo ', n.istitle())
print('O caractere digitado é um decimal ', n.isdecimal())
print('O caractere digitado é um identificador ', n.isidentifier())
print('O caractere digitado é um imprimivel ', n.isprintable())
print('O caractere digitado é um ascii ', n.isascii())
