n1 = float(input("Digite um valor:"))
n2 = float(input("Digite um valor:"))
n2 = float(input("Digite um valor:"))
n3 = float(input("Digite um valor:"))
n4 = float(input("Digite um valor:"))
n5 = float(input("Digite um valor:"))
print("A média dos valores é:",n1+n2+n3+n4+n5/5)